# Stage 1: Build the Vite app
FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_SERVER_URL
ARG VITE_HOME_PATH
ARG VITE_CASHFREE_MODE
ARG VITE_PUBLIC_FIREBASE_API_KEY
ARG VITE_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG VITE_PUBLIC_FIREBASE_PROJECT_ID
ARG VITE_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG VITE_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_PUBLIC_FIREBASE_APP_ID
ARG VITE_PUBLIC_FIREBASE_MEASUREMENT_ID
ARG VITE_GOOGLE_CLIENT_ID

ENV VITE_SERVER_URL=$VITE_SERVER_URL \
    VITE_HOME_PATH=$VITE_HOME_PATH \
    VITE_CASHFREE_MODE=$VITE_CASHFREE_MODE \
    VITE_PUBLIC_FIREBASE_API_KEY=$VITE_PUBLIC_FIREBASE_API_KEY \
    VITE_PUBLIC_FIREBASE_AUTH_DOMAIN=$VITE_PUBLIC_FIREBASE_AUTH_DOMAIN \
    VITE_PUBLIC_FIREBASE_PROJECT_ID=$VITE_PUBLIC_FIREBASE_PROJECT_ID \
    VITE_PUBLIC_FIREBASE_STORAGE_BUCKET=$VITE_PUBLIC_FIREBASE_STORAGE_BUCKET \
    VITE_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$VITE_PUBLIC_FIREBASE_MESSAGING_SENDER_ID \
    VITE_PUBLIC_FIREBASE_APP_ID=$VITE_PUBLIC_FIREBASE_APP_ID \
    VITE_PUBLIC_FIREBASE_MEASUREMENT_ID=$VITE_PUBLIC_FIREBASE_MEASUREMENT_ID \
    VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID

COPY package*.json ./
RUN npm ci --legacy-peer-deps

COPY . .
RUN npm run build

# Stage 2: Lightweight static server
FROM node:20-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist ./dist

EXPOSE 3001

CMD ["serve", "-s", "dist", "-l", "3001"]